### ISSUE TITLE
Change out Diego cell instance types.

### ISSUE THREAD

**Issue by mxplusb** [cloud-gov/product#1289]
In order to properly ensure the platform is performant, we need to review and change out our Diego cell types for more effective VM types.

## Acceptance Criteria
GIVEN we need to change our Diego instance types,
WHEN we review the available instance types,
AND we understand what our options are
THEN we will be able to migrate the Diego cells to the new instance type.

--- 

## Security considerations

None.

## Implementation sketch

Yes.

**Comment by mxplusb** [comment]
Here is a good example of why we want to leverage #1071  before trying to change out instance types:

```
root@PRODUCTION:/tmp/build/8e72821d$ bosh int --path /vm_types/name=minimal <(bosh cloud-config)
cloud_properties:
  ephemeral_disk:
    size: 10240
  instance_type: m4.large
name: minimal

Succeeded
root@PRODUCTION:/tmp/build/8e72821d$ bosh int --path /vm_types/name=small <(bosh cloud-config)
cloud_properties:
  ephemeral_disk:
    size: 10240
  instance_type: m4.large
name: small

Succeeded
root@PRODUCTION:/tmp/build/8e72821d$ bosh int --path /vm_types/name=small-highmem <(bosh cloud-config)
cloud_properties:
  ephemeral_disk:
    size: 10240
  instance_type: r4.xlarge
name: small-highmem
```

Currently the names of the vm types are mismatched aliases, where the `small` vm type and the `minimal` vm type are both the same type of instances: `m4.large`.
