### ISSUE TITLE
Perform BOSH CF Deployments faster

### ISSUE THREAD

**Issue by cweibel** [cloud-gov/product#2466]
In order to make the deployment of Production CF faster, changes to how the `update:` configuration can be made to parallelize the updates.

## Acceptance Criteria

* [ ] Verify the manifest has update blocks for each of the identified instance_groups
* [ ] Run a deploy against production with a stemcell or similar change and observe these changes being done in parallel

--- 

## Security considerations

This should have no positive or negative impacts to security

## Implementation sketch

 - Create an ops file which makes the following changes:

    - diego-cell - max_in_flight: 10%, canaries: 10%           
    - doppler -    max_in_flight: 2, canaries: 2               
    - log-api -    max_in_flight: 2
    - log-cache -  max_in_flight: 2
    - router -     max_in_flight: 2, canaries: 2 

 - Update the pipeline.yml file in cg-deploy-cf to use this ops file 
 - Run a bosh deploy during the next cycle which does a stemcell or other similar change which modifies each vm in the deployment

 - An example of the ops file would look similar to:

   ```
   - type: replace
     path: /instance_groups/name=diego-cell/update?
     value:
       max_in_flight: 10%
       canaries: 10%
   ```
