### ISSUE TITLE
Update all pipelines to use external `cf` resource which currently use it as a builtin resource

### ISSUE THREAD

**Issue by cweibel** [cloud-gov/product#2682]
In order to bump to concourse v7.10.0, we need to modify all the existing pipelines which use the `cf` resource to point to an external resource as it has been deprecated in the newer version.

## Acceptance Criteria
* [ ] No pipelines use a concourse resource called `type: cf`
--- 

## Security considerations
We need this to keep patching concourse going forward

## Implementation sketch
* [ ] find all pipelines with `type: cf`
* [ ] Update the reference to something like `type: cf-external` and add a block similar to:

```
resource_types:
- name: cf-external
  source:
    repository: cloudfoundry-community/cf-resource
    tag: latest
  type: docker-image
```

* [ ] remove pinned version in concourse, redeploy stage/prod, rerun ip tables jobs

Helper script to download all the pipelines and then use editor of choice to skim for `type: cf`:

```
for PIPE in $(fly -t cloud.gov pipelines --json | jq -r ".[].name")
do
    echo "Pipeline: $PIPE"
    fly -t cloud.gov get-pipeline -p $PIPE > $PIPE.yml
done
```

Change your `fly -t cloud.gov...` to match whatever fly alias you have locally
